version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ratelimiter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: ratelimiter-app
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - IP_RATE_LIMIT=10
      - IP_BLOCK_TIME=5m
      - TOKEN_RATE_LIMIT=100
      - TOKEN_BLOCK_TIME=5m
      - PORT=8080
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis-data: